-- Schema-only copy of the operational E-Pesc tables. No Lovable Cloud data or auth records are migrated.
-- Neon has no auth.users: auth_user_id and vendedor_id remain external identity UUIDs, without a foreign key.
-- Roles are held separately from app_users to prevent profile updates from granting privileges.
CREATE TYPE public.app_role AS ENUM ('vendedor', 'administrador', 'root');
CREATE TYPE public.produto_tipo AS ENUM ('inteiro', 'tratado');
CREATE TYPE public.movimento_tipo AS ENUM ('perda', 'quebra', 'outros', 'processamento', 'venda');
CREATE TYPE public.pedido_status AS ENUM ('pendente', 'atendido');
CREATE TYPE public.pagamento_tipo AS ENUM ('avista', 'prazo');
CREATE TYPE public.prepaid_method AS ENUM ('pix', 'cartao', 'dinheiro');

CREATE TABLE public.peixarias (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  razao_social text NOT NULL,
  cpf_cnpj text NOT NULL DEFAULT '',
  proprietario text NOT NULL DEFAULT '',
  whatsapp text NOT NULL DEFAULT '',
  endereco text NOT NULL DEFAULT '',
  cidade text NOT NULL DEFAULT '',
  dia_pagamento integer NOT NULL DEFAULT 10,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  mensalidade numeric NOT NULL DEFAULT 0,
  vendedor_root_id uuid,
  plano_gratuito boolean NOT NULL DEFAULT false,
  desconto_mensalidade numeric NOT NULL DEFAULT 0,
  desconto_mes_referencia text
);
CREATE TABLE public.app_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid,
  name text NOT NULL,
  cpf text NOT NULL DEFAULT '',
  whatsapp text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE
);
CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.app_users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  UNIQUE (user_id, role)
);
ALTER TABLE public.peixarias ADD CONSTRAINT peixarias_vendedor_root_id_fkey FOREIGN KEY (vendedor_root_id) REFERENCES public.app_users(id) ON DELETE SET NULL;

CREATE TABLE public.clientes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  cpf_cnpj text NOT NULL DEFAULT '',
  whatsapp text NOT NULL DEFAULT '',
  endereco text NOT NULL DEFAULT '',
  cidade text NOT NULL DEFAULT '',
  ativo boolean NOT NULL DEFAULT true,
  debito numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE
);
CREATE TABLE public.fornecedores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  cpf_cnpj text NOT NULL DEFAULT '',
  whatsapp text NOT NULL DEFAULT '',
  endereco text NOT NULL DEFAULT '',
  cidade text NOT NULL DEFAULT '',
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE
);
CREATE TABLE public.produtos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sku text NOT NULL,
  nome text NOT NULL,
  tipo public.produto_tipo NOT NULL DEFAULT 'inteiro',
  linked_sku text,
  estoque_kg numeric(12,3) NOT NULL DEFAULT 0,
  preco_compra numeric(12,2) NOT NULL DEFAULT 0,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX produtos_sku_peixaria_unique ON public.produtos (sku, peixaria_id);
CREATE TABLE public.movimentacoes_estoque (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  produto_id uuid NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  tipo public.movimento_tipo NOT NULL,
  kg numeric(12,3) NOT NULL,
  observacao text,
  created_at timestamptz NOT NULL DEFAULT now(),
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE
);
CREATE TABLE public.pedidos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  numero integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  cliente_id uuid NOT NULL REFERENCES public.clientes(id),
  status public.pedido_status NOT NULL DEFAULT 'pendente',
  pagamento public.pagamento_tipo,
  entrada numeric(12,2),
  prepaid boolean NOT NULL DEFAULT false,
  prepaid_method public.prepaid_method,
  valor_total numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  fulfilled_at timestamptz,
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE,
  cancelado boolean NOT NULL DEFAULT false,
  cancelado_motivo text,
  cancelado_at timestamptz,
  cancelado_por uuid
);
CREATE TABLE public.itens_pedido (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pedido_id uuid NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
  produto_id uuid NOT NULL REFERENCES public.produtos(id),
  kg numeric(12,3) NOT NULL,
  preco_kg numeric(12,2) NOT NULL,
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE
);
CREATE TABLE public.vendas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id uuid REFERENCES public.clientes(id),
  vendedor_id uuid,
  produto_id uuid NOT NULL REFERENCES public.produtos(id),
  kg numeric(12,3) NOT NULL,
  preco_kg numeric(12,2) NOT NULL,
  valor_total numeric(12,2) NOT NULL,
  forma_pagamento public.pagamento_tipo NOT NULL DEFAULT 'avista',
  entrada numeric(12,2),
  created_at timestamptz NOT NULL DEFAULT now(),
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE,
  cancelado boolean NOT NULL DEFAULT false,
  cancelado_motivo text,
  cancelado_at timestamptz,
  cancelado_por uuid
);
CREATE TABLE public.itens_venda (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  venda_id uuid NOT NULL REFERENCES public.vendas(id) ON DELETE CASCADE,
  produto_id uuid NOT NULL REFERENCES public.produtos(id),
  kg numeric NOT NULL,
  preco_kg numeric NOT NULL,
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE
);
CREATE TABLE public.dividas_compra (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fornecedor_id uuid REFERENCES public.fornecedores(id),
  produto_id uuid REFERENCES public.produtos(id),
  kg numeric(12,3),
  preco_kg numeric(12,2),
  valor_total numeric(12,2) NOT NULL,
  valor_pago numeric(12,2) NOT NULL DEFAULT 0,
  quitado boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE,
  cancelado boolean NOT NULL DEFAULT false,
  cancelado_motivo text,
  cancelado_at timestamptz,
  cancelado_por uuid,
  descricao text,
  recorrente boolean NOT NULL DEFAULT false,
  mes_referencia text,
  vencimento date
);
CREATE TABLE public.pagamentos_saida (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  divida_id uuid REFERENCES public.dividas_compra(id),
  fornecedor_id uuid REFERENCES public.fornecedores(id),
  valor numeric(12,2) NOT NULL,
  tipo text NOT NULL DEFAULT 'total',
  created_at timestamptz NOT NULL DEFAULT now(),
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE,
  cancelado boolean NOT NULL DEFAULT false,
  cancelado_at timestamptz,
  descricao text,
  cancelado_motivo text,
  cancelado_por uuid
);
CREATE TABLE public.pagamentos_entrada (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id uuid REFERENCES public.clientes(id),
  origem text NOT NULL DEFAULT 'venda',
  pedido_id uuid REFERENCES public.pedidos(id),
  produto_id uuid REFERENCES public.produtos(id),
  kg numeric(12,3),
  valor numeric(12,2) NOT NULL,
  tipo text NOT NULL DEFAULT 'total',
  created_at timestamptz NOT NULL DEFAULT now(),
  venda_id uuid REFERENCES public.vendas(id) ON DELETE SET NULL,
  peixaria_id uuid REFERENCES public.peixarias(id) ON DELETE CASCADE,
  cancelado boolean NOT NULL DEFAULT false,
  cancelado_at timestamptz,
  cancelado_motivo text,
  cancelado_por uuid
);
CREATE TABLE public.pagamentos_mensalidade (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  peixaria_id uuid NOT NULL REFERENCES public.peixarias(id) ON DELETE CASCADE,
  mes_referencia text NOT NULL,
  confirmado boolean NOT NULL DEFAULT false,
  confirmado_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (peixaria_id, mes_referencia)
);
CREATE TABLE public.activity_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  user_name text NOT NULL DEFAULT '',
  action text NOT NULL,
  entity text NOT NULL DEFAULT '',
  entity_id text NOT NULL DEFAULT '',
  amount numeric,
  description text NOT NULL DEFAULT '',
  peixaria_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_activity_logs_peixaria_created ON public.activity_logs (peixaria_id, created_at DESC);
CREATE INDEX idx_activity_logs_action ON public.activity_logs (action);
CREATE INDEX idx_activity_logs_user ON public.activity_logs (user_id);

-- Neon does not have Lovable Cloud's auth.uid() or authenticated role. Fail closed
-- for non-owner database roles; a future authenticated server integration must
-- validate identity and tenant access before querying with the owner connection.
ALTER TABLE public.peixarias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fornecedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimentacoes_estoque ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.itens_pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.itens_venda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dividas_compra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagamentos_saida ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagamentos_entrada ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagamentos_mensalidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;
CREATE TRIGGER update_app_users_updated_at BEFORE UPDATE ON public.app_users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_peixarias_updated_at BEFORE UPDATE ON public.peixarias FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER set_updated_at_clientes BEFORE UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER set_updated_at_fornecedores BEFORE UPDATE ON public.fornecedores FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER set_updated_at_produtos BEFORE UPDATE ON public.produtos FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE FUNCTION public.deduct_stock_on_sale_item() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  UPDATE public.produtos SET estoque_kg = estoque_kg - NEW.kg WHERE id = NEW.produto_id;
  RETURN NEW;
END;
$$;
CREATE TRIGGER deduct_stock_on_sale_item AFTER INSERT ON public.itens_venda FOR EACH ROW EXECUTE FUNCTION public.deduct_stock_on_sale_item();
CREATE FUNCTION public.deduct_stock_on_order_fulfill() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF OLD.status = 'pendente' AND NEW.status = 'atendido' THEN
    UPDATE public.produtos p SET estoque_kg = p.estoque_kg - ip.kg
    FROM public.itens_pedido ip WHERE ip.pedido_id = NEW.id AND p.id = ip.produto_id;
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_deduct_stock_order_fulfill AFTER UPDATE ON public.pedidos FOR EACH ROW EXECUTE FUNCTION public.deduct_stock_on_order_fulfill();
